services:
  _defaults:
    autowire: true
    autoconfigure: true

  app.checker.keywords.common:
    class: Freelance\Checker\KeywordsChecker
    arguments:
      $keywords:
        - 'scrape'
        - 'scrapi'
        - 'crawler'
        - 'crawling'
        - 'extract'
        - 'parser'
        - 'parsing'
        - 'data mining'
        - 'collect'
        - 'парсинг'
        - 'парсер'
        - 'парсити'
        - 'сбор'
        - 'парсить'
        - 'cобрать'
        - 'зібрати'
        - 'scrape'
        - 'scrapi'
        - 'crawler'
        - 'crawling'
        - 'extract'
        - 'parser'
        - 'parsing'
        - 'data mining'
        - 'collect'
        - 'парсе'
        - 'парса'
        - 'парси'
        - 'сбор'
        - 'собрать'
        - 'скрапер'
        - 'скраппер'
        - 'екстрактор'
        - 'экстрактор'
        - 'parser'
        - 'scrape'
        - 'scrapi'
        - 'extract'

  app.checker.keywords.en:
    class: Freelance\Checker\KeywordsChecker
    arguments:
      $keywords:
        - 'scrape'
        - 'scrapi'
        - 'crawler'
        - 'crawling'
        - 'extract'
        - 'parser'
        - 'parsing'
        - 'data mining'
        - 'collect'

  app.checker.keywords.uk:
    class: Freelance\Checker\KeywordsChecker
    arguments:
      $keywords:
        - 'парсинг'
        - 'парсер'
        - 'парсити'
        - 'сбор'
        - 'парсить'
        - 'cобрать'
        - 'зібрати'
        - 'scrape'
        - 'scrapi'
        - 'crawler'
        - 'crawling'
        - 'extract'
        - 'parser'
        - 'parsing'
        - 'data mining'
        - 'collect'

  app.checker.keywords.ru:
    class: Freelance\Checker\KeywordsChecker
    arguments:
      $keywords:
        - 'парсе'
        - 'парса'
        - 'парси'
        - 'сбор'
        - 'собрать'
        - 'скрапер'
        - 'скраппер'
        - 'екстрактор'
        - 'экстрактор'
        - 'parser'
        - 'scrape'
        - 'scrapi'
        - 'extract'
