services:


  app.command.download_src:
    class: Freelance\Command\DownloadSrcCommand
    arguments:
      $loader: '@app.loader'
    tags:
      - { name: 'console.command', command: 'app:download-src' }


  app.command.scrapper_base:
    abstract: true
    class: Freelance\Command\CheckFeedCommand
    arguments:
      $jobRepository: '@Freelance\Repository\JobRepository'
      $checker: '@app.checker.keywords.common'

  app.command.upwork_rss_reader_scraping:
    parent: 'app.command.scrapper_base'
    arguments:
      $feed: '@app.feed.upwork_com'
    tags:
      - { name: 'console.command', command: 'app:upwork_rss_reader_scraping' }

  app.command.free_lance_ua_page_scraping:
    parent: 'app.command.scrapper_base'
    arguments:
      $feed: '@app.feed.free_lance_ua'
    tags:
      - { name: 'console.command', command: 'app:free_lance_ua_scraping' }

  app.command.freelance_com_feed_scraping:
    parent: 'app.command.scrapper_base'
    arguments:
      $feed: '@app.feed.freelance_com'
    tags:
      - { name: 'console.command', command: 'app:freelance_com_scraping' }

  app.command.freelancehunt_ua_feed_scraping:
    parent: 'app.command.scrapper_base'
    arguments:
      $feed: '@app.feed.freelancehunt_ua'
    tags:
      - { name: 'console.command', command: 'app:freelancehunt_ua_scraping' }

  app.command.freelance_ua_feed_scraping:
    parent: 'app.command.scrapper_base'
    arguments:
      $feed: '@app.feed.freelance_ua'
    tags:
      - { name: 'console.command', command: 'app:freelance_ua_scraping' }

#  app.command.flru_rss_reader_scraping: FUCKING russia
#    parent: 'app.command.scrapper_base'
#    arguments:
#      $feed: '@app.feed.fl_ru'
#    tags:
#      - { name: 'console.command', command: 'app:flru_rss_reader_scraping' }

  app.command.notifier_telegram:
    class: Freelance\Command\NotifierCommand
    arguments:
      $jobPositionRepository: '@Freelance\Repository\JobPositionRepository'
      $jobRepository: '@Freelance\Repository\JobRepository'
      $notifier: '@app.notifier.telegram'
      $logger: '@logger'
    tags:
      - { name: 'console.command', command: 'app:notifier_telegram' }