services:
  _defaults:
    autowire: true
    autoconfigure: true

  app.feed.upwork_com:
    class: Freelance\Feed\UpworkComFeed
    arguments:
      $loader: '@app.loader'

  app.feed.fl_ru:
    class: Freelance\Feed\FlRuFeed
    arguments:
      $loader: '@app.loader'

  app.feed.free_lance_ua:
    class: Freelance\Feed\Free_LanceUaFeed
    arguments:
      $loader: '@app.loader'

  app.feed.freelance_com:
    class: Freelance\Feed\FreelanceComFeed
    arguments:
      $loader: '@app.loader'

  app.feed.freelance_ua:
    class: Freelance\Feed\FreelanceUaFeed
    arguments:
      $loader: '@app.loader'

  app.feed.freelancehunt_ua:
    class: Freelance\Feed\FreelanceHuntUaFeed
    arguments:
      $loader: '@app.loader'
