services:
  _defaults:
    autowire: true
    autoconfigure: true

  app.notifier.telegram:
    class: Freelance\Notifier\TelegramNotifier
    arguments:
      $notifier: '@Symfony\Component\Notifier\NotifierInterface'
      $template: '@app.template.markdown'
