parameters:
  env(TELEGRAM_USER_ID): ''
  my_telegram_user_id: '%env(TELEGRAM_USER_ID)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  app.telegram.request_factory:
    class: Http\Factory\Guzzle\RequestFactory

  app.telegram.stream_factory:
    class: Http\Factory\Guzzle\StreamFactory

  app.telegram.guzzle_client:
    class: Http\Adapter\Guzzle6\Client

  app.telegram.api_client:
    class: TgBotApi\BotApiBase\ApiClient
    arguments:
      $requestFactory: '@app.telegram.request_factory'
      $streamFactory: '@app.telegram.stream_factory'
      $client: '@app.telegram.guzzle_client'

  app.telegram.normalizer:
    class: TgBotApi\BotApiBase\BotApiNormalizer

  app.telegram.bot_freelance_scraper:
    class: TgBotApi\BotApiBase\BotApi
    arguments:
      $botKey: '%telegram_bot_key_freelance_scraper%'
      $apiClient: '@app.telegram.api_client'
      $normalizer: '@app.telegram.normalizer'
