version: '2.4'
services:

  freelance-rss-parser-php-worker:
    build:
      context: ${PATH_TO_FREELANCE_RSS_PARSER_PHP}
      dockerfile: environment/docker/worker-dev.dockerfile
      args:
        MIDDLEWARE_VERSION: ${FREELANCE_RSS_PARSER_PHP_MIDDLEWARE_VERSION}
    restart: on-failure
    image: freelance-rss-parser-php-worker:dev
    user: ${CURRENT_UID}
    volumes:
      - ${PATH_TO_FREELANCE_RSS_PARSER_PHP}:/app
      - ${PATH_TO_COMPOSER_CACHE}:/.composer
      - ${PATH_TO_FREELANCE_RSS_PARSER_PHP}/environment/php/${APP_ENVIRONMENT}/docker-php-ext-xdebug-0.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug-0.ini
      - ${PATH_TO_FREELANCE_RSS_PARSER_PHP}/environment/php/${APP_ENVIRONMENT}/zzz_php_extend.ini:/usr/local/etc/php/conf.d/zzz_php_extend.ini
    environment:
      COMPOSER_AUTH: ${COMPOSER_AUTH}
      VERSON: dev
      APP_NAME: freelance-rss-parser-php-worker
      SENTRY_DSN: ${FREELANCE_RSS_PARSER_SENTRY_DSN}
      APP_ENV: ${SYMFONY_APP_ENV}
      APP_DEBUG: ${SYMFONY_DEBUG}
      APP_SECRET: ${FREELANCE_RSS_PARSER_PHP_SECRET}
      TELEGRAM_BOT_FREELANCE_SCRAPER: ${FREELANCE_TELEGRAM_BOT_FREELANCE_SCRAPER}
      TELEGRAM_USER_ID: ${FREELANCE_TELEGRAM_USER_ID}
      FEED_UPWORK_RSS_SCRAPING: ${FREELANCE_RSS_PARSER_UPWORK_FEED_SCRAPING}
      FEED_UPWORK_RSS_DATA_EXTRACTION: ${FREELANCE_RSS_PARSER_UPWORK_FEED_DATA_EXTRACTION}
      FEED_UPWORK_RSS_WEB_SCRAPING: ${FREELANCE_RSS_PARSER_UPWORK_FEED_WEB_SCRAPING}
      FEED_UPWORK_RSS_WEB_RESEARCH: ${FREELANCE_RSS_PARSER_UPWORK_FEED_WEB_RESEARCH}
      FEED_UPWORK_RSS_WEB_CRAWLER: ${FREELANCE_RSS_PARSER_UPWORK_FEED_WEB_CRAWLER}
      FEED_FLRU_RSS_SCRAPING: ${FREELANCE_RSS_PARSER_FLRU_FEED_SCRAPING}
      STORAGE_HOST: ${STORAGE_HOST_FREELANCE_RSS_PARSER}
      STORAGE_PORT: ${STORAGE_PORT_FREELANCE_RSS_PARSER}
      STORAGE_USER: ${STORAGE_USER_FREELANCE_RSS_PARSER}
      STORAGE_PASS: ${STORAGE_PASS_FREELANCE_RSS_PARSER}
      STORAGE_DB: ${STORAGE_DB_FREELANCE_RSS_PARSER}