version: '2.4'
services:

  freelance-rss-parser-php:
    build:
      context: ${PATH_TO_FREELANCE_RSS_PARSER_PHP}
      dockerfile: environment/docker/php.dockerfile
      args:
        PHP_IMAGE: ${FREELANCE_RSS_PARSER_PHP_VERSION}
    image: freelance-rss-parser-php:${FREELANCE_RSS_PARSER_PHP_MIDDLEWARE_VERSION}

  freelance-rss-parser-php-worker:
    build:
      context: ${PATH_TO_FREELANCE_RSS_PARSER_PHP}
      dockerfile: environment/docker/worker.dockerfile
      args:
        MIDDLEWARE_VERSION: ${FREELANCE_RSS_PARSER_PHP_MIDDLEWARE_VERSION}
        COMPOSER_AUTH: ${COMPOSER_AUTH}
        PRIVATE_REPOSITORY_USERNAME: ${PRIVATE_REPOSITORY_USERNAME}
        PRIVATE_REPOSITORY_PASSWORD: ${PRIVATE_REPOSITORY_PASSWORD}
        PRIVATE_REPOSITORY_HOST: ${PRIVATE_REPOSITORY_HOST}
        PRIVATE_REPOSITORY_PATH: ${PRIVATE_REPOSITORY_PATH_FREELANCE_RSS_PARSER_PHP}
        APP_VERSION: ${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    image: freelance-rss-parser-php-worker:${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    depends_on:
      - freelance-rss-parser-php

  freelance-rss-parser-php-worker-upwork_rss_reader_scraping:
    build:
      context: ${PATH_TO_FREELANCE_RSS_PARSER_PHP}
      dockerfile: environment/docker/upwork_rss_reader_scraping.dockerfile
      args:
        APP_VERSION: ${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    image: freelance-rss-parser-php-worker-upwork_rss_reader_scraping:${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    depends_on:
      - freelance-rss-parser-php-worker

  freelance-rss-parser-php-worker-upwork_rss_reader_data_extraction:
    build:
      context: ${PATH_TO_FREELANCE_RSS_PARSER_PHP}
      dockerfile: environment/docker/upwork_rss_reader_data_extraction.dockerfile
      args:
        APP_VERSION: ${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    image: freelance-rss-parser-php-worker-upwork_rss_reader_data_extraction:${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    depends_on:
      - freelance-rss-parser-php-worker

  freelance-rss-parser-php-worker-upwork_rss_reader_web_scraping:
    build:
      context: ${PATH_TO_FREELANCE_RSS_PARSER_PHP}
      dockerfile: environment/docker/upwork_rss_reader_web_scraping.dockerfile
      args:
        APP_VERSION: ${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    image: freelance-rss-parser-php-worker-upwork_rss_reader_web_scraping:${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    depends_on:
      - freelance-rss-parser-php-worker

  freelance-rss-parser-php-worker-upwork_rss_reader_web_research:
    build:
      context: ${PATH_TO_FREELANCE_RSS_PARSER_PHP}
      dockerfile: environment/docker/upwork_rss_reader_web_research.dockerfile
      args:
        APP_VERSION: ${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    image: freelance-rss-parser-php-worker-upwork_rss_reader_web_research:${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    depends_on:
      - freelance-rss-parser-php-worker

  freelance-rss-parser-php-worker-upwork_rss_reader_web_crawler:
    build:
      context: ${PATH_TO_FREELANCE_RSS_PARSER_PHP}
      dockerfile: environment/docker/upwork_rss_reader_web_crawler.dockerfile
      args:
        APP_VERSION: ${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    image: freelance-rss-parser-php-worker-upwork_rss_reader_web_crawler:${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    depends_on:
      - freelance-rss-parser-php-worker

  freelance-rss-parser-php-worker-flru_rss_reader_scraping:
    build:
      context: ${PATH_TO_FREELANCE_RSS_PARSER_PHP}
      dockerfile: environment/docker/flru_rss_reader_scraping.dockerfile
      args:
        APP_VERSION: ${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    image: freelance-rss-parser-php-worker-flru_rss_reader_scraping:${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    depends_on:
      - freelance-rss-parser-php-worker

  freelance-rss-parser-php-worker-notifier_telegram:
    build:
      context: ${PATH_TO_FREELANCE_RSS_PARSER_PHP}
      dockerfile: environment/docker/notifier_telegram.dockerfile
      args:
        APP_VERSION: ${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    image: freelance-rss-parser-php-worker-notifier_telegram:${FREELANCE_RSS_PARSER_PHP_WORKER_VERSION}
    depends_on:
      - freelance-rss-parser-php-worker