parameters:
  'env(SENTRY_DSN)': ''

  setry_dsn: '%env(SENTRY_DSN)%'

sentry:
  dsn: '%setry_dsn%'
  options:
    environment: '%kernel.environment%'
    release: '%app.version%' #your app version

services:
  _defaults:
    autowire: true
    autoconfigure: true

  sentry.monolog.handler:
    class: Sentry\Monolog\Handler
    arguments:
      $level: 'ERROR'

  Monolog\Processor\TagProcessor:
    arguments:
      $tags:
        app: '%app.name%'
    tags:
      - { name: monolog.processor }